[tool.poetry]
name = "d&d"
version = "0.1.0"
description = ""
authors = ["Farshad Sanginnezhad <fxfix3r@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
